//! Fragment provenance — *where a fragment came from*.
//!
//! Provenance is first-class in Nameless (PRD §6: "Provenance and lineage are first class").
//! It drives which lifecycle path a fragment travels through the state machine: human-recorded,
//! derived, and sampled material travels the *human* path (capture → analyze → place …), while
//! `ai_generated` material must pass the eval gate (generate → evaluate → promote → place).
//!
//! The complete 4-variant set is defined NOW (Phase 1) even though `Sampled` is not exercised
//! until Phase 8. Locking the enum early is cheap and means later phases extend behavior, not
//! the type — the attribution gate that further restricts a `Sampled` placement (Phase 8) bolts
//! onto this without a type change.

use serde::{Deserialize, Serialize};

/// Where a fragment's audio originated.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Provenance {
    /// Recorded by the producer (a hum, a hook, a beat). Travels the human lifecycle.
    HumanRecorded,
    /// Generated by a model, conditioned on the producer's material. Must pass the eval gate.
    AiGenerated,
    /// Mechanically derived from another fragment (e.g. a transform/bounce). Human lifecycle.
    Derived,
    /// Promoted from a stem in the persistent sample library (Phase 8). Human lifecycle, but
    /// placement additionally requires complete attribution (the Phase-8 attribution gate).
    Sampled,
}

impl Provenance {
    /// All variants — used by the exhaustive transition-matrix tests and any UI enumeration.
    pub const ALL: [Provenance; 4] = [
        Provenance::HumanRecorded,
        Provenance::AiGenerated,
        Provenance::Derived,
        Provenance::Sampled,
    ];

    /// True for provenances that travel the *human* lifecycle (no eval gate).
    ///
    /// `HumanRecorded`, `Derived`, and `Sampled` are all real source audio — there is nothing to
    /// score generated-vs-source fidelity against — so they do not pass through the AI eval gate.
    /// (`Sampled` instead clears an attribution gate at placement time, added in Phase 8.)
    pub const fn travels_human_path(self) -> bool {
        matches!(
            self,
            Provenance::HumanRecorded | Provenance::Derived | Provenance::Sampled
        )
    }

    /// True only for `AiGenerated` — the provenance that must clear the eval gate before placement.
    pub const fn is_ai(self) -> bool {
        matches!(self, Provenance::AiGenerated)
    }

    /// Stable lowercase string form, matching the Postgres `provenance` enum labels and the serde
    /// representation. Pure (no serde round-trip needed) so the DB adapter can map without pulling
    /// `serde_json` into a hot path.
    pub const fn as_str(self) -> &'static str {
        match self {
            Provenance::HumanRecorded => "human_recorded",
            Provenance::AiGenerated => "ai_generated",
            Provenance::Derived => "derived",
            Provenance::Sampled => "sampled",
        }
    }

    /// Parse from the canonical string form (DB enum label). Returns `None` for unknown labels.
    pub fn from_db_str(s: &str) -> Option<Provenance> {
        match s {
            "human_recorded" => Some(Provenance::HumanRecorded),
            "ai_generated" => Some(Provenance::AiGenerated),
            "derived" => Some(Provenance::Derived),
            "sampled" => Some(Provenance::Sampled),
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_contains_every_variant_once() {
        assert_eq!(Provenance::ALL.len(), 4);
    }

    #[test]
    fn human_path_excludes_ai_only() {
        assert!(Provenance::HumanRecorded.travels_human_path());
        assert!(Provenance::Derived.travels_human_path());
        assert!(Provenance::Sampled.travels_human_path());
        assert!(!Provenance::AiGenerated.travels_human_path());
        assert!(Provenance::AiGenerated.is_ai());
    }

    #[test]
    fn as_str_round_trips_through_from_db_str() {
        for p in Provenance::ALL {
            assert_eq!(Provenance::from_db_str(p.as_str()), Some(p));
        }
        assert_eq!(Provenance::from_db_str("nonsense"), None);
    }
}
